.\" Manpage for smartcheck by nobody <nobody>

.TH "smartcheck" "1" "2013-12-04" "nobody" "Rsync backup"

.SH NAME

smartcheck - SMART-Werte prüfen und bei kritischen Werten warnen

.SH SYNOPSIS

smartcheck

.SH DESCRIPTION

SMART-Werte prüfen und bei kritischen Werten warnen.

.SH EXAMPLE

	smartcheck && rsync-backup

