#!/bin/sh

set -e

cryptsetup="$(which cryptsetup)" || cryptsetup="/usr/sbin/cryptsetup"
partitions="$(sed -ne 's#.*\([sh]d[a-zA-Z0-9]\+$\)#/dev/\1#p' /proc/partitions)"

# dbackup/drestore
dpkg --get-selections >"$HOME/dpkg-selections"
debconf-get-selections >"$HOME/debconf-selections"
apt-mark showmanual >"$HOME/apt-mark-showmanual"

# crypsetup
for i in $partitions; do
	$cryptsetup isLuks "$i" || continue
	filepath="$HOME/$(basename "$i").luksHeaderBackup"
	rm -f -- "$filepath"
	$cryptsetup luksHeaderBackup "$i" --header-backup-file "$filepath"
done

